image: node:20.9.0

pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build:demo
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - main

